### ISSUE TITLE
Add Raw to BufferedSource Converter

### ISSUE THREAD

**Issue by digitalbuddha** [NYTimes/Store#190]
Some users have asked for the ability to work with the `FileSystemPersister` when going from a raw that is already a Pojo or String for example a fetcher coming from `Retrofit`.  The initial proposal to create a `FileSystemPersister` which takes as input a raw to bufferedsouce converter ie:
```
userPojo->Okio.buffer(Okio.source(new ByteArrayInputStream(adapter.toJson(value)
      .getBytes(StandardCharsets.UTF_8))));
```

This way someone can configure a Store to take in a Pojo yet still work with our FileSystem.

**Comment by saket** [comment]
I was just going to open an issue for this. I use a library that internally wraps in a set of APIs and does not expose their response bodies. This means that I can only use a `RealStoreBuilder<Parsed, Parsed, Key>` by using `StoreBuilder.key()`. Additionally, I want to use an object other than `Barcode` as the key because I want to have complex cache keys. Both these constraints mean that I will have to implement my own disk Persister.

In order to do that, I have been going through your code to understand what exactly are the pre-defined persisters like `SourcePersister` and `FileSystemPersister` are doing. So far I've realized that the filesystem module is tightly coupled with `Barcode`, which I feel is not right. Please correct me if I'm wrong.

The presence of a class named as `FileSystem` is also a small source of confusion, because Okio also uses a similar class with the same name. This cost me some time because I was trying to figure out how to use a BufferedSource, which you claim to be much faster.

Your Droidcon Italy talk convinced me to use Store, but I'm kinda struggling out in some places, partly because the library is low on documentation :)

**Comment by digitalbuddha** [comment]
Filesystem is in no way ties to Barcodes.  Take a look at https://github.com/NYTimes/Store/blob/develop/filesystem/src/main/java/com/nytimes/android/external/fs/FileSystemPersisterFactory.java#L74 as this is a FileSystemPersister that can work with any key type.  The reason we use BufferedSource is that it allows streaming in a manner similar to Reader. As for naming, sorry nothing we can do about that now ☺️

Not sure if you had a question in there I did not answer.

**Comment by saket** [comment]
Yes! Sadly `FileSystemPersister` is hardcoded to `BufferedSource`, which means I cannot use because I can only use `StoreBuilder.key()`. :( 

I'm trying to follow `FileSystemPersisterFactory` for creating a custom persister which also implements `Clearable` and `RecordProvider`, but I'm unable to understand how are the `expirationDuration` and `expiration` being passed to the `create()` method. Can you please help me out with this? I was under the assumption that a `Store` would handle passing in these values internally from the configured cache policies.

Also, thanks for the quick reply!

**Comment by saket** [comment]
Update: This is what I came up with: https://gist.github.com/Saketme/f57befdcd0423e6812d7230c6a8ba36e

Does this look correct to you?

**Comment by digitalbuddha** [comment]
will comment on gist.

**Comment by digitalbuddha** [comment]
The task for this issue is to make an RxJava Transformer (both rx1 and rx2 branch), this would allow someone to do

```
builder.
fetcher(new Fetcher().compose(new objectToSourceConverter(new TwoWayParserAdapter()))
```
This way no changes need to be made to the Store but users will be able to use Fetchers that do not output a `BufferedSource` 

`TwoWayParserAdapter` should implement a BufferedParser interface that has a toJson and a fromJson method.

The rest of the transformer will look something like: 
```
userPojo->Okio.buffer(Okio.source(new ByteArrayInputStream(adapter.toJson(value)
      .getBytes(StandardCharsets.UTF_8))));
```
