### ISSUE TITLE
Does subclassing `RealStore` and overriding `get` also modify the behavior of `fetch`, `stream`, and `getRefreshing`?

### ISSUE THREAD

**Issue by lalunamel** [NYTimes/Store#201]
Hi there!

I'm interested in subclassing `Store` like Mike Nakhimovich explains, [here](https://www.youtube.com/watch?v=G1MebI2k9aA&feature=youtu.be&t=26m30s), because I have a JSON object with data and a list of ids of dependent JSON objects I'd also like to fetch.

Will subclassing `RealStore` and overriding `get` to grab an object and it's dependent objects also modify the behavior of `fetch`, `stream`, and `getRefreshing` for my store? 

It looks like, based on the implementation of `RealStore`, overriding `get` will not change the behavior of the other methods because the implementations of those other methods do not depend upon `get`, they depend upon methods defined on the variable `internalStore`.

Is this true? If so, how can I make it so that say, calling `fetch` will also retrieve dependent data?
~~I'd like to have my store methods all return the same kinds of data.~~ I'd like all the `Store` methods on my subclass to return the same observable-combination of values, like the ones in the above video.

**Comment by digitalbuddha** [comment]
Hello! Mike here... Subclassing Get will not affect fetch but it will however affect getRefreshing since that is a get with a user initiated refresh.  Subclassing fetch would affect how get works since get calls fetch if nothing is in cache.  

For your last question, if I understand correctly you want to have storeA call get anytime storeB calls get and storeA call fetch anytime storeB calls fetch then override get and fetch  both and flatmap/merge the one store get call with the others stores Get call and the one Fetch call with the other stores fetch call.  Sorry no comp to make an example but will be home in a week if you still need help.  Thanks for using library.

**Comment by lalunamel** [comment]
Howdy - thanks for taking the time on the weekend to respond to my issue!

There was only one question in my issue, and I've corrected the last bit that may have made it seem like there were two.

Okay, so if I'm understanding right, if I want the same data (a combination/massaging of observables) out of all my store methods, all of `get`, `fetch`, and `stream` will have to be overridden.

**Comment by digitalbuddha** [comment]
Yup! But I found that only overriding get with proper cache policies should be sufficient for most case.
