### ISSUE TITLE
Convert store to kotlin 

### ISSUE THREAD

**Issue by digitalbuddha** [NYTimes/Store#213]
Rxjava2 branch should be converted to kotlin for readability. Now that there is first class support I see no reason to continue in Java

**Comment by pavlospt** [comment]
@charbgr was just thinking of forking Store and "konverting" it :P We can surely help in this area :)

**Comment by digitalbuddha** [comment]
I'm waiting for the readall/deleteall pr to make it in and then we will
cherry pick it in and be ready for conversion. Thank you for offering to
help, will totally take you up on it 😀

On May 17, 2017 11:57 PM, "Pavlos-Petros Tournaris" <
notifications@github.com> wrote:

@charbgr <https://github.com/charbgr> was just thinking of forking Store
and "konverting" it :P We can surely help in this area :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/NYTimes/Store/issues/213#issuecomment-302229407>, or mute
the thread

**Comment by pavlospt** [comment]
Great, ping us when ready :D

**Comment by stoyicker** [comment]
I don't want to come to ruin the party, but my out-of-the-blue two cents: is there really a strong reason to convert the codebase to Kotlin, or even use it at all? I'm a fan of the language myself, but I wonder if the benefit it brings is worth the trade-off in this particular case. Library modules should keep the classpath as clean as possible, and even if Kotlin is now a supported language for Android, by including the stdlib ([~6.3k methods last time I checked](http://www.methodscount.com/?lib=org.jetbrains.kotlin%3Akotlin-stdlib%3A1.1.2-4)) in the library you'll be forcing it into the classpath regardless of whether the host app uses Kotlin or not, which may be especially bad if the app doesn't use ProGuard.
I would very much endorse the use of Kotlin for non-production variants (say tests, for example) however, since the stdlib wouldn't need to go into the classpath in this case.

**Comment by digitalbuddha** [comment]
All valid points.  Some of the rational is to open up kotlin features like better DSL for instantiation and reified generic support.  It would also be nice to the the nullability types and val/var.  I guess its all nice to have instead of need to have.

**Comment by digitalbuddha** [comment]
Closing as a good reason has not been established as to why.

**Comment by stoyicker** [comment]
just a quick-add, I'd be happy to 'donate' the bindings library if you guys want to put it in this repo and distribute it in a way more aligned than the rest of the artifacts (instead of for example jitpack).

**Comment by digitalbuddha** [comment]
Yes that would be great. Would give others an opportunity to add more kotlin extensions too. Want to make a new module as a pr?

**Comment by stoyicker** [comment]
sure! I'll also take the chance to add some tests for what's there already
