### ISSUE TITLE
Spike: Create DSL for Store Instatiation

### ISSUE THREAD

**Issue by digitalbuddha** [NYTimes/Store#216]
Right now we use Builders to instantiate a Store.  Jake Wharton gave a talk at I/O detailing how you can create a custom DSL using Kotlin to instantiate objects.
For reference: https://youtu.be/fPzxfeDJDzY?t=17m39s

Ideally we should be able to do something like:

val myStore = store{
    fetcher(myFetcher)
    persister(myPersister)
    parser(myParser)
}

I'm unclear how this works with generics so we nee to explore that part.

**Comment by stoyicker** [comment]
I suggest a different artifact, `store-kotlin-extensions` or something, to implement this sort of things, and then we can consider if we want to merge it into the core. In addition, I've made a DSL using Kotlin before (once :D), and I'd be glad to take care of this one if I may.
Also, for reference, another relevant video: https://news.realm.io/news/kau-jake-wharton-testing-robots/

**Comment by stoyicker** [comment]
I've done a draft of how things would look wrt store building: https://github.com/stoyicker/store-kotlin-bindings ([direct link to example](https://github.com/stoyicker/store-kotlin-bindings/blob/f15b3fbc098a3ccfd5966839121fd065fe506a5b/sample/src/main/kotlin/org/jorge/store/kotlin/sample/MainActivity.kt)).
If someone takes a look and has any feedback, let me know. If all looks good I can add some more things that I think could be made better-looking with Kotlin :D

**Comment by digitalbuddha** [comment]
looks beautiful! I love how you got rid of the generics in the
StoreBuilder!  I'll review tomorrow and have some comments.

**Comment by digitalbuddha** [comment]
I like your implementation. Any chance you want to get it on maven proper so I can use it without jitpack, we can link it from Readme ☺️

**Comment by stoyicker** [comment]
Following the conversation from #213 since it's more appropriate here I guess: I'm having some problems wrt to tests: I want to write a custom `equals` for the tests as an extension function of `RealStore` that delegates (eventually) to `RealInternalStore` and compares its parser, cache, etc. However `internalStore` in `RealStore` is private, and I would like to avoid using reflection. Can I include in the pr making the field pp and marking it @VisibleForTesting so that I can fix the tests? Any better ideas?

**EDIT:** nvm, '_solved_' it

**Comment by digitalbuddha** [comment]
closed by #229
