### ISSUE TITLE
Fetch a store with a webservice that return a whole store insead of a single store unit 

### ISSUE THREAD

**Issue by afaucogney** [NYTimes/Store#274]
Let have a strore

`mProductCatalogStore: Store<Product, String>`

and the API

```
    @GET("/products")
    fun getProducts(): Single<List<Product>>

    @GET("/product")
    fun getProduct(@Query("id") id: String): Single<Product>
```

When I init the store, 

    init {
        productCatalogStore = StoreBuilder
                .key<String, Product>()
                .fetcher({ id ->
                    mPickingApi
                            .create(ProductApi::class.java)
                            .getProduct(id)
                })
                .open()

    }

Imagine I have millions of Product, and I have a Ws that may download this big bunch of data in a single WS call. How can I do that with Store ?

**Comment by stoyicker** [comment]
Store instances can only encompass one of the calls to your API because the mapping store to fetcher is 1:1. You need a different store for the use case you describe, since it uses another method of your API. That would be something like:

```
init {
    productCatalogStore = StoreBuilder
            .key<Unit, List<Product>>()
            .fetcher({ _ ->
                mPickingApi
                        .create(ProductApi::class.java)
                        .getProducts()
            })
            .open()
}
```
You probably want to not to recreate the api in every store also, but that's another topic.
Finally, since you're using Kotlin, I'll take the chance to recommend you checking out [the Kotlin DSL artifact](https://github.com/NYTimes/Store/tree/feature/rx2/store-kotlin).

**Comment by digitalbuddha** [comment]
Did @stoyicker answer your question? if not please restate
