### ISSUE TITLE
How to do a batch query with list?

### ISSUE THREAD

**Issue by diousk** [NYTimes/Store#299]
Hi,

Our API service supports query item with a list of id like: (with Retrofit)
`
@GET("/api/users")
`
`
Single<List<User>> getBatchUser(@Query("ids") List<String> userIds)
`

I'm wondering if there's a easy way to query a batch of keys (BarCode) in Store like
`
#"List<String> userIds" transforms to "List<BarCode> barCodes"
`
`
Single<List<User>> users = UserStore.get(barCodes)
`

and internally retrieve from the memory/disk for non-expired User objects,
provide the expired or non-cached BarCode items to the fetcher 
so that I can use the original API to do a batch query
finally combine the fetched objects with the non-expired cached objects

I don't want to lose the original single query caching, i.e. UserStore.get(barCode)

Is it possible to do this and have only one Store?

Thanks.

**Comment by digitalbuddha** [comment]
Rather than using barcode you can use your own Key which can be a list of ids. Store is agnostic to what your key type is, Store simply passes your key to your fetcher. Hope that helps. Let me know if you need an example.  Similar you can create your own implementation of Persister which can save/retrieve your batch in any way you want.

**Comment by diousk** [comment]
Got it, thanks for explanation
