### ISSUE TITLE
Clear Memory Fails

### ISSUE THREAD

**Issue by PaulWoitaschek** [NYTimes/Store#96]
After clearing the memory a following call to `get` should make a new request. But it doesn't

See #95

**Comment by digitalbuddha** [comment]
Fix will be to reset the persister when clear memory is called and the persister is a no op persister.

**Comment by PaulWoitaschek** [comment]
Btw; I don't use a persister yet as I need a way to clear both memory and persister for a barcode. 

Also I need to specify for how long persisted data is valid so I don't use stale data.

**Comment by digitalbuddha** [comment]
That's great for me  because it is opposite if my use case and found all these problems!  As for the stale persister problem does the following work as solution for you: we make new StaleAwarePersister that has an additional callback for isStale(key). If true it will skip loading from disk. There's an issue for it if you have other ideas requirements. Thanks for using ☺️

**Comment by PaulWoitaschek** [comment]
Thanks for building it @digitalbuddha :)

I explained my usecase here #68
